# Generated by Django 3.1.7 on 2021-04-16 06:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generateRoomCode, max_length=6, unique=True),
        ),
    ]
